### ISSUE TITLE
Workflow fetches an old version of GLuaTest

### ISSUE THREAD

**Issue by TomDotBat** [CFC-Servers/GLuaTest#19]
![image](https://user-images.githubusercontent.com/11298466/189527294-2ffae9cc-6b97-45d9-8039-c7d1f9748fb6.png)

Latest tag is currently 0.15, not 0.9.2. 

Here is the workflow I am using:
```yml
name: gLuaTest

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-tests:
    uses: CFC-Servers/GLuaTest/.github/workflows/run_tests.yml@main
```
